--
title: Welcome 
author: Usamoto
email: your-email@domain.com
theme: minima
description: Maybe there's a little something happening right here. 
This is gonna be a happy little seascape. That easy. I'm sort of a softy, I couldn't shoot Bambi except with a camera. 
Automatically, all of these beautiful, beautiful things will happen.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
--
